istio:
  enabled: true
  prometheusRule:
    IstioSidecarMemModerate: true
    IstioSidecarMemHigh: true
    IstioConfigValidationFailed: true
    Istio5XXResponseCode: true
    IstioSidecarEndpointError: true
    IstioSidecarListenerConflict: true
