istio:
  enabled: true
prometheusRule:
  IstioSidecarMemModerate: true
  IstioSidecarMemHigh: true
  Istio5XXResponseCode: true
  IstioSidecarEndpointError: true
  IstioSidecarListenerConflict: true
  IstioAmbientReadinessProbeFailures: true
  IstioTCPConnectionFailures: true
