# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: Prometheus Operator admission webhook patch jobs
templates:
  - charts/upstream/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
  - charts/upstream/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
release:
  name: monitoring
  namespace: monitoring
tests:
  - it: does not render patch jobs by default
    asserts:
      - hasDocuments:
          count: 0
