// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :exec
WITH removed AS (
    DELETE FROM auth_sessions
    WHERE expires_at <= now()
       OR token_hash = $3::bytea
       OR token_hash IN (
           SELECT token_hash FROM auth_sessions ORDER BY expires_at DESC OFFSET 127
       )
)
INSERT INTO auth_sessions (token_hash, expires_at)
VALUES ($1, $2)
`

type CreateAuthSessionParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	OldHash   []byte
}

// Replace the browser's previous session and keep at most 128 recent sessions.
func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession, arg.TokenHash, arg.ExpiresAt, arg.OldHash)
	return err
}

const deleteAuthSession = `-- name: DeleteAuthSession :exec
DELETE FROM auth_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteAuthSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteAuthSession, tokenHash)
	return err
}

const validAuthSession = `-- name: ValidAuthSession :one
SELECT EXISTS (
    SELECT 1 FROM auth_sessions
    WHERE token_hash = $1 AND expires_at > now()
)
`

func (q *Queries) ValidAuthSession(ctx context.Context, tokenHash []byte) (bool, error) {
	row := q.db.QueryRow(ctx, validAuthSession, tokenHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
