// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalog.sql

package db

import (
	"context"
)

const getRelease = `-- name: GetRelease :one
SELECT tag, chart_version, domain
FROM releases
WHERE tag = $1 AND deleted_at IS NULL
`

type GetReleaseRow struct {
	Tag          string
	ChartVersion string
	Domain       string
}

func (q *Queries) GetRelease(ctx context.Context, tag string) (GetReleaseRow, error) {
	row := q.db.QueryRow(ctx, getRelease, tag)
	var i GetReleaseRow
	err := row.Scan(&i.Tag, &i.ChartVersion, &i.Domain)
	return i, err
}

const listImages = `-- name: ListImages :many
SELECT
    image_id,
    package_key,
    name,
    ref,
    registry,
    digest,
    when_kind,
    signature,
    critical_count,
    high_count,
    ironbank,
    scanned
FROM images
WHERE release_tag = $1 AND deleted_at IS NULL
ORDER BY package_key, name
`

type ListImagesRow struct {
	ImageID       string
	PackageKey    string
	Name          string
	Ref           string
	Registry      string
	Digest        string
	WhenKind      string
	Signature     string
	CriticalCount *int32
	HighCount     *int32
	Ironbank      string
	Scanned       bool
}

func (q *Queries) ListImages(ctx context.Context, releaseTag string) ([]ListImagesRow, error) {
	rows, err := q.db.Query(ctx, listImages, releaseTag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImagesRow
	for rows.Next() {
		var i ListImagesRow
		if err := rows.Scan(
			&i.ImageID,
			&i.PackageKey,
			&i.Name,
			&i.Ref,
			&i.Registry,
			&i.Digest,
			&i.WhenKind,
			&i.Signature,
			&i.CriticalCount,
			&i.HighCount,
			&i.Ironbank,
			&i.Scanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackages = `-- name: ListPackages :many
SELECT key, enabled, image_count
FROM packages
WHERE release_tag = $1 AND deleted_at IS NULL
ORDER BY key
`

type ListPackagesRow struct {
	Key        string
	Enabled    bool
	ImageCount int32
}

func (q *Queries) ListPackages(ctx context.Context, releaseTag string) ([]ListPackagesRow, error) {
	rows, err := q.db.Query(ctx, listPackages, releaseTag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackagesRow
	for rows.Next() {
		var i ListPackagesRow
		if err := rows.Scan(&i.Key, &i.Enabled, &i.ImageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT
    r.tag,
    r.chart_version,
    COALESCE((
        SELECT count(*)::int FROM packages p
        WHERE p.release_tag = r.tag AND p.enabled AND p.deleted_at IS NULL
    ), 0)::int AS enabled,
    COALESCE((
        SELECT count(*)::int FROM packages p
        WHERE p.release_tag = r.tag AND NOT p.enabled AND p.deleted_at IS NULL
    ), 0)::int AS disabled
FROM releases r
WHERE r.deleted_at IS NULL
ORDER BY r.tag
`

type ListReleasesRow struct {
	Tag          string
	ChartVersion string
	Enabled      int32
	Disabled     int32
}

func (q *Queries) ListReleases(ctx context.Context) ([]ListReleasesRow, error) {
	rows, err := q.db.Query(ctx, listReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleasesRow
	for rows.Next() {
		var i ListReleasesRow
		if err := rows.Scan(
			&i.Tag,
			&i.ChartVersion,
			&i.Enabled,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteImages = `-- name: SoftDeleteImages :exec
UPDATE images
SET deleted_at = now()
WHERE release_tag = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteImages(ctx context.Context, releaseTag string) error {
	_, err := q.db.Exec(ctx, softDeleteImages, releaseTag)
	return err
}

const softDeletePackages = `-- name: SoftDeletePackages :exec
UPDATE packages
SET deleted_at = now()
WHERE release_tag = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePackages(ctx context.Context, releaseTag string) error {
	_, err := q.db.Exec(ctx, softDeletePackages, releaseTag)
	return err
}

const upsertImage = `-- name: UpsertImage :exec
INSERT INTO images (
    release_tag, image_id, package_key, name, ref, registry, digest,
    when_kind, signature, critical_count, high_count, ironbank, scanned
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13
)
ON CONFLICT (release_tag, image_id) DO UPDATE
SET package_key = EXCLUDED.package_key,
    name = EXCLUDED.name,
    ref = EXCLUDED.ref,
    registry = EXCLUDED.registry,
    digest = EXCLUDED.digest,
    when_kind = EXCLUDED.when_kind,
    signature = EXCLUDED.signature,
    critical_count = EXCLUDED.critical_count,
    high_count = EXCLUDED.high_count,
    ironbank = EXCLUDED.ironbank,
    scanned = EXCLUDED.scanned,
    deleted_at = NULL
`

type UpsertImageParams struct {
	ReleaseTag    string
	ImageID       string
	PackageKey    string
	Name          string
	Ref           string
	Registry      string
	Digest        string
	WhenKind      string
	Signature     string
	CriticalCount *int32
	HighCount     *int32
	Ironbank      string
	Scanned       bool
}

func (q *Queries) UpsertImage(ctx context.Context, arg UpsertImageParams) error {
	_, err := q.db.Exec(ctx, upsertImage,
		arg.ReleaseTag,
		arg.ImageID,
		arg.PackageKey,
		arg.Name,
		arg.Ref,
		arg.Registry,
		arg.Digest,
		arg.WhenKind,
		arg.Signature,
		arg.CriticalCount,
		arg.HighCount,
		arg.Ironbank,
		arg.Scanned,
	)
	return err
}

const upsertPackage = `-- name: UpsertPackage :exec
INSERT INTO packages (release_tag, key, enabled, image_count)
VALUES ($1, $2, $3, $4)
ON CONFLICT (release_tag, key) DO UPDATE
SET enabled = EXCLUDED.enabled,
    image_count = EXCLUDED.image_count,
    deleted_at = NULL
`

type UpsertPackageParams struct {
	ReleaseTag string
	Key        string
	Enabled    bool
	ImageCount int32
}

func (q *Queries) UpsertPackage(ctx context.Context, arg UpsertPackageParams) error {
	_, err := q.db.Exec(ctx, upsertPackage,
		arg.ReleaseTag,
		arg.Key,
		arg.Enabled,
		arg.ImageCount,
	)
	return err
}

const upsertRelease = `-- name: UpsertRelease :exec
INSERT INTO releases (tag, chart_version, domain)
VALUES ($1, $2, $3)
ON CONFLICT (tag) DO UPDATE
SET chart_version = EXCLUDED.chart_version,
    domain = EXCLUDED.domain,
    deleted_at = NULL
`

type UpsertReleaseParams struct {
	Tag          string
	ChartVersion string
	Domain       string
}

func (q *Queries) UpsertRelease(ctx context.Context, arg UpsertReleaseParams) error {
	_, err := q.db.Exec(ctx, upsertRelease, arg.Tag, arg.ChartVersion, arg.Domain)
	return err
}
