// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: connection.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteClusterConnection = `-- name: DeleteClusterConnection :exec
DELETE FROM cluster_connection WHERE id = 1
`

func (q *Queries) DeleteClusterConnection(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteClusterConnection)
	return err
}

const getClusterConnection = `-- name: GetClusterConnection :one
SELECT name, context, server, kubeconfig, updated_at FROM cluster_connection WHERE id = 1
`

type GetClusterConnectionRow struct {
	Name       string
	Context    string
	Server     string
	Kubeconfig []byte
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetClusterConnection(ctx context.Context) (GetClusterConnectionRow, error) {
	row := q.db.QueryRow(ctx, getClusterConnection)
	var i GetClusterConnectionRow
	err := row.Scan(
		&i.Name,
		&i.Context,
		&i.Server,
		&i.Kubeconfig,
		&i.UpdatedAt,
	)
	return i, err
}

const saveClusterConnection = `-- name: SaveClusterConnection :exec
INSERT INTO cluster_connection (id, name, context, server, kubeconfig)
VALUES (1, $1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, context = EXCLUDED.context, server = EXCLUDED.server,
    kubeconfig = EXCLUDED.kubeconfig, updated_at = now()
`

type SaveClusterConnectionParams struct {
	Name       string
	Context    string
	Server     string
	Kubeconfig []byte
}

func (q *Queries) SaveClusterConnection(ctx context.Context, arg SaveClusterConnectionParams) error {
	_, err := q.db.Exec(ctx, saveClusterConnection,
		arg.Name,
		arg.Context,
		arg.Server,
		arg.Kubeconfig,
	)
	return err
}
