// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type Finding struct {
	ID            int64
	Digest        string
	Ref           string
	DbVersion     string
	CriticalCount int32
	HighCount     int32
	Cves          string
	CreatedAt     pgtype.Timestamptz
}

type Image struct {
	ReleaseTag    string
	ImageID       string
	PackageKey    string
	Name          string
	Ref           string
	Registry      string
	Digest        string
	WhenKind      string
	Signature     string
	CriticalCount *int32
	HighCount     *int32
	Ironbank      string
	Scanned       bool
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type Package struct {
	ReleaseTag string
	Key        string
	Enabled    bool
	ImageCount int32
	CreatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type Release struct {
	Tag          string
	ChartVersion string
	Domain       string
	CreatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type ScanJob struct {
	ID         string
	ReleaseTag string
	Scope      string
	State      string
	Total      int32
	Done       int32
	Failed     int32
	Skipped    int32
	Error      string
	CreatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type ScanJobItem struct {
	JobID   string
	ImageID string
	Ref     string
	Digest  string
	State   string
	Error   string
}

type ScanSetting struct {
	Singleton bool
	AutoClean bool
}
