// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveJobs = `-- name: CountActiveJobs :one
SELECT count(*)::int AS count
FROM scan_jobs
WHERE state IN ('queued', 'running')
`

func (q *Queries) CountActiveJobs(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveJobs)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const finishJob = `-- name: FinishJob :exec
UPDATE scan_jobs
SET state = $2, done = $3, failed = $4, skipped = $5, error = $6, finished_at = now()
WHERE id = $1
`

type FinishJobParams struct {
	ID      string
	State   string
	Done    int32
	Failed  int32
	Skipped int32
	Error   string
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.Exec(ctx, finishJob,
		arg.ID,
		arg.State,
		arg.Done,
		arg.Failed,
		arg.Skipped,
		arg.Error,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, release_tag, scope, state, total, done, failed, skipped, error, created_at, finished_at
FROM scan_jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (ScanJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.ReleaseTag,
		&i.Scope,
		&i.State,
		&i.Total,
		&i.Done,
		&i.Failed,
		&i.Skipped,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getSBOM = `-- name: GetSBOM :one
SELECT CASE WHEN $1::text = 'cyclonedx' THEN sbom_cyclonedx ELSE sbom_spdx END::bytea AS document
FROM findings WHERE id = $2
`

type GetSBOMParams struct {
	Format string
	ID     int64
}

func (q *Queries) GetSBOM(ctx context.Context, arg GetSBOMParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSBOM, arg.Format, arg.ID)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const getSettings = `-- name: GetSettings :one
SELECT auto_clean
FROM scan_settings
WHERE singleton
`

func (q *Queries) GetSettings(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var auto_clean bool
	err := row.Scan(&auto_clean)
	return auto_clean, err
}

const insertFinding = `-- name: InsertFinding :exec
INSERT INTO findings (digest, ref, db_version, critical_count, high_count, cves, sbom_cyclonedx, sbom_spdx, sbom_error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertFindingParams struct {
	Digest        string
	Ref           string
	DbVersion     string
	CriticalCount int32
	HighCount     int32
	Cves          string
	SbomCyclonedx []byte
	SbomSpdx      []byte
	SbomError     string
}

func (q *Queries) InsertFinding(ctx context.Context, arg InsertFindingParams) error {
	_, err := q.db.Exec(ctx, insertFinding,
		arg.Digest,
		arg.Ref,
		arg.DbVersion,
		arg.CriticalCount,
		arg.HighCount,
		arg.Cves,
		arg.SbomCyclonedx,
		arg.SbomSpdx,
		arg.SbomError,
	)
	return err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO scan_jobs (id, release_tag, scope, state, total)
VALUES ($1, $2, $3, $4, $5)
`

type InsertJobParams struct {
	ID         string
	ReleaseTag string
	Scope      string
	State      string
	Total      int32
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.Exec(ctx, insertJob,
		arg.ID,
		arg.ReleaseTag,
		arg.Scope,
		arg.State,
		arg.Total,
	)
	return err
}

const insertJobItem = `-- name: InsertJobItem :exec
INSERT INTO scan_job_items (job_id, image_id, ref, state)
VALUES ($1, $2, $3, $4)
`

type InsertJobItemParams struct {
	JobID   string
	ImageID string
	Ref     string
	State   string
}

func (q *Queries) InsertJobItem(ctx context.Context, arg InsertJobItemParams) error {
	_, err := q.db.Exec(ctx, insertJobItem,
		arg.JobID,
		arg.ImageID,
		arg.Ref,
		arg.State,
	)
	return err
}

const interruptItems = `-- name: InterruptItems :exec
UPDATE scan_job_items
SET state = 'failed', error = 'interrupted'
WHERE state IN ('queued', 'running')
`

func (q *Queries) InterruptItems(ctx context.Context) error {
	_, err := q.db.Exec(ctx, interruptItems)
	return err
}

const interruptJobs = `-- name: InterruptJobs :exec
UPDATE scan_jobs
SET state = 'failed', error = 'interrupted', finished_at = now()
WHERE state IN ('queued', 'running')
`

func (q *Queries) InterruptJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, interruptJobs)
	return err
}

const latestFindings = `-- name: LatestFindings :many
SELECT DISTINCT ON (digest)
    id,
    digest,
    ref,
    db_version,
    critical_count,
    high_count,
    cves,
    created_at,
    (sbom_cyclonedx IS NOT NULL AND sbom_spdx IS NOT NULL)::boolean AS sbom_available,
    sbom_error
FROM findings
ORDER BY digest, created_at DESC
`

type LatestFindingsRow struct {
	ID            int64
	Digest        string
	Ref           string
	DbVersion     string
	CriticalCount int32
	HighCount     int32
	Cves          string
	CreatedAt     pgtype.Timestamptz
	SbomAvailable bool
	SbomError     string
}

func (q *Queries) LatestFindings(ctx context.Context) ([]LatestFindingsRow, error) {
	rows, err := q.db.Query(ctx, latestFindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestFindingsRow
	for rows.Next() {
		var i LatestFindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Digest,
			&i.Ref,
			&i.DbVersion,
			&i.CriticalCount,
			&i.HighCount,
			&i.Cves,
			&i.CreatedAt,
			&i.SbomAvailable,
			&i.SbomError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobItems = `-- name: ListJobItems :many
SELECT image_id, ref, digest, state, error
FROM scan_job_items
WHERE job_id = $1
ORDER BY image_id
`

type ListJobItemsRow struct {
	ImageID string
	Ref     string
	Digest  string
	State   string
	Error   string
}

func (q *Queries) ListJobItems(ctx context.Context, jobID string) ([]ListJobItemsRow, error) {
	rows, err := q.db.Query(ctx, listJobItems, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobItemsRow
	for rows.Next() {
		var i ListJobItemsRow
		if err := rows.Scan(
			&i.ImageID,
			&i.Ref,
			&i.Digest,
			&i.State,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, release_tag, scope, state, total, done, failed, skipped, error, created_at, finished_at
FROM scan_jobs
ORDER BY created_at DESC
LIMIT 30
`

func (q *Queries) ListJobs(ctx context.Context) ([]ScanJob, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanJob
	for rows.Next() {
		var i ScanJob
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseTag,
			&i.Scope,
			&i.State,
			&i.Total,
			&i.Done,
			&i.Failed,
			&i.Skipped,
			&i.Error,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedItems = `-- name: ListQueuedItems :many
SELECT image_id, ref, digest, state, error
FROM scan_job_items
WHERE job_id = $1 AND state = 'queued'
ORDER BY image_id
`

type ListQueuedItemsRow struct {
	ImageID string
	Ref     string
	Digest  string
	State   string
	Error   string
}

func (q *Queries) ListQueuedItems(ctx context.Context, jobID string) ([]ListQueuedItemsRow, error) {
	rows, err := q.db.Query(ctx, listQueuedItems, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueuedItemsRow
	for rows.Next() {
		var i ListQueuedItemsRow
		if err := rows.Scan(
			&i.ImageID,
			&i.Ref,
			&i.Digest,
			&i.State,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobRunning = `-- name: MarkJobRunning :execrows
UPDATE scan_jobs
SET state = 'running'
WHERE id = $1 AND state = 'queued'
`

func (q *Queries) MarkJobRunning(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markJobRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextQueuedJob = `-- name: NextQueuedJob :one
SELECT id
FROM scan_jobs
WHERE state = 'queued'
ORDER BY created_at
LIMIT 1
`

func (q *Queries) NextQueuedJob(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, nextQueuedJob)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setAutoClean = `-- name: SetAutoClean :exec
UPDATE scan_settings
SET auto_clean = $1
WHERE singleton
`

func (q *Queries) SetAutoClean(ctx context.Context, autoClean bool) error {
	_, err := q.db.Exec(ctx, setAutoClean, autoClean)
	return err
}

const touchJob = `-- name: TouchJob :exec
UPDATE scan_jobs
SET done = $2, failed = $3, skipped = $4
WHERE id = $1
`

type TouchJobParams struct {
	ID      string
	Done    int32
	Failed  int32
	Skipped int32
}

func (q *Queries) TouchJob(ctx context.Context, arg TouchJobParams) error {
	_, err := q.db.Exec(ctx, touchJob,
		arg.ID,
		arg.Done,
		arg.Failed,
		arg.Skipped,
	)
	return err
}

const updateJobItem = `-- name: UpdateJobItem :exec
UPDATE scan_job_items
SET state = $3, error = $4, digest = $5
WHERE job_id = $1 AND image_id = $2
`

type UpdateJobItemParams struct {
	JobID   string
	ImageID string
	State   string
	Error   string
	Digest  string
}

func (q *Queries) UpdateJobItem(ctx context.Context, arg UpdateJobItemParams) error {
	_, err := q.db.Exec(ctx, updateJobItem,
		arg.JobID,
		arg.ImageID,
		arg.State,
		arg.Error,
		arg.Digest,
	)
	return err
}
