apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-inventory
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [get, list]
  - apiGroups: [networking.istio.io]
    resources: [virtualservices, gateways]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-inventory
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-inventory
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- range $namespace := append .Values.cluster.releaseNamespaces .Values.cluster.namespace | uniq }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Release.Namespace }}-{{ $.Release.Name }}-helm-read
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: [secrets, configmaps]
    verbs: [get, list]
  {{- if eq $namespace $.Values.cluster.namespace }}
  - apiGroups: [helm.toolkit.fluxcd.io]
    resources: [helmreleases]
    verbs: [get, list]
  - apiGroups: [source.toolkit.fluxcd.io]
    resources: [gitrepositories]
    verbs: [get, list]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Namespace }}-{{ $.Release.Name }}-helm-read
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $.Release.Namespace }}-{{ $.Release.Name }}-helm-read
subjects:
  - kind: ServiceAccount
    name: {{ $.Release.Name }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
