# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: disallow-auto-mount-service-account-token-cel ValidatingPolicy
templates:
  - templates/other-vpol/disallow-auto-mount-service-account-token-cel.yaml

capabilities:
  apiVersions:
    - policies.kyverno.io/v1
tests:
  - it: should render both documents when enabled
    set:
      enabled: true
      celPoliciesBeta:
        disallow-auto-mount-service-account-token-cel:
          enabled: true
    asserts:
      - hasDocuments:
          count: 2
      - equal:
          path: metadata.name
          value: disallow-auto-mount-service-account-token-cel
        documentIndex: 0
      - equal:
          path: metadata.name
          value: disallow-auto-mount-service-account-token-cel-serviceaccounts
        documentIndex: 1
      - equal:
          path: spec.matchConstraints.resourceRules[0].resources[0]
          value: pods
        documentIndex: 0
      - equal:
          path: spec.matchConstraints.resourceRules[0].resources[0]
          value: serviceaccounts
        documentIndex: 1

  - it: should not render when disabled
    set:
      enabled: true
      celPoliciesBeta:
        disallow-auto-mount-service-account-token-cel:
          enabled: false
    asserts:
      - hasDocuments:
          count: 0

  - it: should not render when global enabled is false
    set:
      enabled: false
      celPoliciesBeta:
        disallow-auto-mount-service-account-token-cel:
          enabled: true
    asserts:
      - hasDocuments:
          count: 0
