# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: require-istio-on-namespaces-cel ValidatingPolicy
templates:
  - templates/other-vpol/require-istio-on-namespaces-cel.yaml

capabilities:
  apiVersions:
    - policies.kyverno.io/v1
tests:
  - it: should render when enabled
    set:
      enabled: true
      celPoliciesBeta:
        require-istio-on-namespaces-cel:
          enabled: true
    asserts:
      - isKind:
          of: ValidatingPolicy
      - equal:
          path: metadata.name
          value: require-istio-on-namespaces-cel
      - equal:
          path: spec.matchConstraints.resourceRules[0].resources[0]
          value: namespaces
      - notExists:
          path: spec.autogen

  - it: should not render when disabled
    set:
      enabled: true
      celPoliciesBeta:
        require-istio-on-namespaces-cel:
          enabled: false
    asserts:
      - hasDocuments:
          count: 0

  - it: should not render when global enabled is false
    set:
      enabled: false
      celPoliciesBeta:
        require-istio-on-namespaces-cel:
          enabled: true
    asserts:
      - hasDocuments:
          count: 0

  - it: excludes namespace resources by metadata.name
    set:
      enabled: true
      celPoliciesBeta:
        excludeNamespaces:
          - kube-system
        require-istio-on-namespaces-cel:
          enabled: true
          excludeNamespaces:
            - istio-system
    asserts:
      - equal:
          path: spec.matchConditions[0].expression
          value: '!(object.metadata.name in ["kube-system","istio-system"])'
