# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: require-ro-rootfs-cel ValidatingPolicy
templates:
  - templates/other-vpol/require-ro-rootfs-cel.yaml

capabilities:
  apiVersions:
    - policies.kyverno.io/v1
tests:
  - it: should render when enabled
    set:
      enabled: true
      celPoliciesBeta:
        require-ro-rootfs-cel:
          enabled: true
    asserts:
      - isKind:
          of: ValidatingPolicy
      - equal:
          path: metadata.name
          value: require-ro-rootfs-cel

  - it: should not render when disabled
    set:
      enabled: true
      celPoliciesBeta:
        require-ro-rootfs-cel:
          enabled: false
    asserts:
      - hasDocuments:
          count: 0

  - it: should not render when global enabled is false
    set:
      enabled: false
      celPoliciesBeta:
        require-ro-rootfs-cel:
          enabled: true
    asserts:
      - hasDocuments:
          count: 0
