# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: restrict-seccomp-cel ValidatingPolicy
templates:
  - templates/pod-security-vpol/baseline/restrict-seccomp-cel.yaml

capabilities:
  apiVersions:
    - policies.kyverno.io/v1
tests:
  - it: should not render when disabled (default)
    asserts:
      - hasDocuments:
          count: 0

  - it: should not render when global enabled is false
    set:
      enabled: false
      celPoliciesBeta:
        restrict-seccomp-cel:
          enabled: true
    asserts:
      - hasDocuments:
          count: 0

  - it: should render when enabled
    set:
      celPoliciesBeta:
        restrict-seccomp-cel:
          enabled: true
    asserts:
      - isKind:
          of: ValidatingPolicy
      - isAPIVersion:
          of: policies.kyverno.io/v1
      - equal:
          path: metadata.name
          value: restrict-seccomp-cel
