{{- $name := "disallow-istio-injection-bypass-cel" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.celPoliciesBeta) }}
apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disallow Istio Injection Bypass
    policies.kyverno.io/category: Best Practices (Security)
    policies.kyverno.io/severity: {{ default "low" (dig $name "severity" nil .Values.celPoliciesBeta) }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The Istio service mesh uses a sidecar to encrypt traffic. Unless an application is
      managing its own encrypted traffic, Istio should be used. This policy validates
      that Pods do not have the sidecar.istio.io/inject label or annotation set to false.
    policies.bigbang.dev/lifecycle: beta
    policies.bigbang.dev/origin: https://repo1.dso.mil/big-bang/product/packages/kyverno-policies
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "bb-kyverno-policies.validationActions" (merge (dict "name" $name) .) | indent 2 }}
  failurePolicy: {{ include "bb-kyverno-policies.vpol-failurePolicy" (merge (dict "name" $name) .) }}
  {{- include "bb-kyverno-policies.cel-webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  {{- include "bb-kyverno-policies.cel-autogenControllers" (merge (dict "name" $name) .) | indent 2 }}
  evaluation:
    background:
      enabled: {{ include "bb-kyverno-policies.cel-background" (merge (dict "name" $name) .) }}
  {{- if dig $name "matchConstraints" nil .Values.celPoliciesBeta }}
  matchConstraints:
    {{- toYaml (dig $name "matchConstraints" nil .Values.celPoliciesBeta) | nindent 4 }}
  {{- else }}
  matchConstraints:
    resourceRules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["pods"]
  {{- end }}
  {{- $nsExclude := include "bb-kyverno-policies.cel-excludeNamespaces" (merge (dict "name" $name) .) -}}
  {{- $userConditions := dig $name "matchConditions" nil .Values.celPoliciesBeta -}}
  {{- if or $nsExclude $userConditions }}
  matchConditions:
    {{- if $nsExclude }}
    {{- $nsExclude | nindent 4 }}
    {{- end }}
    {{- with $userConditions }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  variables:
  - name: labels
    expression: "object.metadata.?labels.orValue({})"
  - name: annotations
    expression: "object.metadata.?annotations.orValue({})"
  validations:
    - expression: >-
        !variables.labels.exists(k, k == 'sidecar.istio.io/inject' && variables.labels[k] == 'false') &&
        !variables.annotations.exists(k, k == 'sidecar.istio.io/inject' && variables.annotations[k] == 'false')
      message: >-
        The sidecar.istio.io/inject label or annotation cannot be false.
{{- end -}}
