{{- $name := "disallow-pod-exec-cel" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.celPoliciesBeta) }}
apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disallow Pod Exec
    policies.kyverno.io/category: Best Practices (Security)
    policies.kyverno.io/severity: {{ default "medium" (dig $name "severity" nil .Values.celPoliciesBeta) }}
    policies.kyverno.io/subject: PodExecOptions
    policies.kyverno.io/description: >-
      The `exec` and `attach` command may be used to gain shell access, or run other commands, in a
      container. While this can be useful for troubleshooting purposes, it could represent an attack
      vector and is discouraged.  This policy prevents pod exec and attach.
    policies.bigbang.dev/lifecycle: beta
    policies.bigbang.dev/origin: https://repo1.dso.mil/big-bang/product/packages/kyverno-policies
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "bb-kyverno-policies.validationActions" (merge (dict "name" $name) .) | indent 2 }}
  failurePolicy: {{ include "bb-kyverno-policies.vpol-failurePolicy" (merge (dict "name" $name) .) }}
  {{- include "bb-kyverno-policies.cel-webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  evaluation:
    background:
      enabled: {{ include "bb-kyverno-policies.cel-background" (merge (dict "name" $name) .) }}
  {{- if dig $name "matchConstraints" nil .Values.celPoliciesBeta }}
  matchConstraints:
    {{- toYaml (dig $name "matchConstraints" nil .Values.celPoliciesBeta) | nindent 4 }}
  {{- else }}
  matchConstraints:
    resourceRules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CONNECT"]
        resources:   ["pods/exec", "pods/attach"]
  {{- end }}
  {{- $nsExclude := include "bb-kyverno-policies.cel-excludeNamespaces" (merge (dict "name" $name) .) -}}
  {{- $userConditions := dig $name "matchConditions" nil .Values.celPoliciesBeta -}}
  {{- if or $nsExclude $userConditions }}
  matchConditions:
    {{- if $nsExclude }}
    {{- $nsExclude | nindent 4 }}
    {{- end }}
    {{- with $userConditions }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  validations:
    - expression: "false"
      message: "Cannot exec or attach to pods."
{{- end -}}
